language: python
python:
  - "3.9"
install:
  - pip install -r requirements.txt
script: python --version
deploy:
  provider: heroku
  api_key:
    secure: 47bb4f74-c66f-4126-a75e-a6d9a20a2088
  app: books-api-python
  on:
    branch: main