language: python
python:
  - "3.9"
install:
  - pip install -r requirements.txt
script: python --version
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: books-api-python
  on:
    branch: main