language: python
python:
  - "3.9"
install:
  - pip install -r requirements.txt
script: python --version
deploy:
  provider: heroku
  api_key:
    secure: "84d0340f-9a53-4d4e-a9f4-4674b2fcfcea"
  app: books-api-python