language: python
python:
  - "3.9"
install:
  - pip install -r requirements.txt
script: python --version
deploy:
  provider: heroku
  api_key:
    secure: heroku_app_key
  app: books-api-python
  on:
    branch: main